server:
  port: 7070
  servlet:
    context-path: /oauth2-resource

mybatis:
    type-aliases-package: com.chang.model

mapper:
    mappers:
        - com.chang.base.BaseMapper
    not-empty: false
    identity: MYSQL

logging:
  level:
    com.chang.mapper: DEBUG

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://111.225.223.17:3306/oauth2_server?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: eKBLT4v!NxvC8Rb&
      max-active: 50
      initial-size: 10
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        config:
          enabled: true
#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: |
#          -----BEGIN PUBLIC KEY-----
#          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuO6+3x4DV5XQ4z16jGVLfdDolccUubUh3umRrID6Eo/h5xXD4GxuXyiXFNckqkfG/qnZGYZB0k/Il7ifEvIEzP3ifZ6mprDpFjNX9EjfpCCf3LFj8JvsPsuMcBtqyY7WywOAMyiqQNyH9vpkjPc04urtBsehv0LIW7TqCBYS8zruM90NlyyUBciphV0MQugj5DuzJwYrYLhmJNTwx82/CuVMpfFdfI/Hj3IpTisCIKi+b+YhnksMLsgHwt+9kpFmKiqJjNnqO/mreH9uq9b/TV0sQhJpQp7T+dPHaqd0usU4jobT+BSiGH1gZJiPIDsX4F7UD3Tx0+jMyzoBIhfHNwIDAQAB
#          -----END PUBLIC KEY-----