server:
  port: 6060
  servlet:
    context-path: /ui

security:
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      auto-approve-scopes:
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      user-info-uri: http://localhost:7070/oauth2-resource/api/users
      prefer-token-info: true
